apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: 482053628475.dkr.ecr.eu-central-1.amazonaws.com/usupport-admin-api:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: admin-secrets
        - configMapRef:
            name: admin-config
        ports:
        - containerPort: 3007
      imagePullSecrets:
      - name: regcred
